---
name: Python Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.14"
        system:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      PYTHON_VERSION: ${{matrix.python-version}}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - run: pip${{matrix.python-version}} install -e .
      - run: pip${{matrix.python-version}} install vmklib>=2.0.12
      - run: mk python-editable

      - run: mk python-sa-types

      - run: mk docs version=3.6.9
        if: |
          matrix.python-version == '3.14'
          && matrix.system == 'ubuntu-latest'

      - name: lint and build
        run: mk python-lint python-sa yaml python-build-once
        env:
          PY_LINT_MYPY_EXTRA_ARGS: --no-incremental

      - run: mk python-test
        env:
          PY_TEST_EXTRA_ARGS: --cov-report=xml --full-trace

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{secrets.CODECOV_TOKEN}}
          slug: libre-embedded/vcorelib

      - run: mk pypi-upload-ci
        env:
          TWINE_USERNAME: __token__
        if: |
          matrix.python-version == '3.14'
          && matrix.system == 'ubuntu-latest'
          && env.TWINE_PASSWORD != ''
          && github.ref_name == 'master'

      - run: |
          mk python-release owner=libre-embedded \
                            repo=vcorelib version=3.6.9
        if: |
          matrix.python-version == '3.14'
          && matrix.system == 'ubuntu-latest'
          && env.GITHUB_API_TOKEN != ''
          && github.ref_name == 'master'
